### ISSUE TITLE
Add option to accept/finish quests with one click/button

### ISSUE THREAD

**Issue by TalasNetrag** [Ellypse/Storyline#30]
It would be nice to have the option to accept and finish quest with one click or button.
Right clicking takes 3 clicks to accept a quest and finishing takes 2 clicks.

**Comment by Zarggg** [comment]
You can use the Blizzard quest window to accomplish this. There is a setting to toggle whether it is hidden or not.

**Comment by Ellypse** [comment]
I will add to the previous comment that the goal for Storyline is to offer a better experience to read the quest text, not to skip it. Adding such feature goes against the goal of the addon.
