### ISSUE TITLE
Add tutorial popup on first run for scrolling choice frame

### ISSUE THREAD

**Issue by djdanrx80** [Ellypse/Storyline#36]
When asking a guard for directions, some of the features the original wow game has is not included in the storyline addon as you can see below. I had to remove the add on to simply be able to find trainers :( 

![image](https://user-images.githubusercontent.com/42523551/44313612-8c303380-a3d9-11e8-899f-4ba31f8a1ed1.png) 
![image](https://user-images.githubusercontent.com/42523551/44313617-97835f00-a3d9-11e8-91d3-018afbb16dee.png)

**Comment by Solanya** [comment]
You can use the mouse wheel on the selection list to scroll the list.

**Comment by Ellypse** [comment]
We should add a tutorial popup that is shown the first time the user is in this situation to tell them they can scroll using the scroll wheel.

Also related issue #4 to add an option to show the scrollbar (currently here and interactive, but not visible)

**Comment by Ellypse** [comment]
Version 3.1.2 introduced tutorials to inform users that they can scroll on the list when more options are available.
