### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by emanueol** [Ellypse/Storyline#46]
version Storyline-3.1.3.zip 
Wow Classic 

Hi, since today, or very recently, I no longer see Storyline window.
When i talk to NPCs I only see old quest window :(
Not sure what to do..

**Comment by Ellypse** [comment]
Hello.

The version to use for Classic is 1.13.x. Versions 3.x are intended for Retail.

[Here's the latest Classic version to download on Curse](https://www.curseforge.com/wow/addons/storyline/files/2772129).

![image](https://user-images.githubusercontent.com/9035119/69576314-4db9f900-0fcc-11ea-801d-b120201b4e19.png)

**Comment by emanueol** [comment]
Oh its a Twitch problem :( 
Twich supports us selecting both WoW _retail_ and _classic_ and to only display proper addons on each like classic versions always start with 1.xxx but now i see in Twich _classic_ Storyline appearing as 8.2.5 :(

**Comment by emanueol** [comment]
I manually downloaded Storyline-1.13.2.2.zip and working as expected.
Will pay attention in Twich to the version next time.. Hope someone fixes it somehow so Twich will not list retail addons while selected _rclassic_ option.

Thanks for the workaround.

**Comment by Ellypse** [comment]
Thanks for the additional info. I have seen this issue appear sometimes in the Twitch app, which is indeed unfortunate 😕
