### ISSUE TITLE
cannot accept or turn in quests at all

### ISSUE THREAD

**Issue by SLinxTheFox** [Ellypse/Storyline#59]
I just got this addon, it looks beautiful, but it makes the game completely unplayable. any advice or tips? i doubt the addon is just actually broken for everybody since i don't see other issues like this here

**Comment by Ellypse** [comment]
I am not able to reproduce this issue. Please provide more informations about what exactly is broken, not possible to do or displaying incorrectly.

**Comment by Ellypse** [comment]
Closed for lack of info.
