### ISSUE TITLE
Display issue when trying to enter Torghast

### ISSUE THREAD

**Issue by Ellypse** [Ellypse/Storyline#65]
When trying to enter Torghast, Storyline is shown with empty dialog choices instead of the Thorgast frame.

![image](https://user-images.githubusercontent.com/9035119/100380511-4c743f80-3017-11eb-95b0-a0d63a835967.png)

![image](https://user-images.githubusercontent.com/9035119/100380527-539b4d80-3017-11eb-88c5-eac6a574f459.png)

**Comment by Flanell88** [comment]
This problem is up again with 10.0 DF.
