### ISSUE TITLE
Prompt doesn't advance when needing to pick between 2+ rewards

### ISSUE THREAD

**Issue by miltykiss** [Ellypse/Storyline#66]
After updating to 3.2.5 (released recently), attempting to finish a quest that has multiple rewards doesn't seem to advance the Storyline window. Quests where there are 0-1 reward seem to work fine.

Notes:
- Version 3.2.5
- Also occurs when only Storyline is active
- Screenshot: [https://i.imgur.com/PCUhN8S.jpg](url)

**Comment by Ellypse** [comment]
Thanks for the report. I just released version 3.2.5.1 which has a hotfix for this issue.

**Comment by miltykiss** [comment]
Yay, fix confimed. Thank you for the quick fix!
