### ISSUE TITLE
Storyline background dark

### ISSUE THREAD

**Issue by Lakuzia** [Ellypse/Storyline#70]
I'm wondering why the like outline? is dark for me.

![image](https://user-images.githubusercontent.com/48613820/101314507-86122b00-380d-11eb-87a7-7dae0f81ef7b.png)

**Comment by Ellypse** [comment]
You are using another addon that is skinning storyline. The position of the buttons in the bottom right corner is not the default one. It could be ElvUI or ConsolePort.
